<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <ProjectReference Include="../../SharedKernel/Cinema.SharedKernel.csproj" />
    <ProjectReference Include="../../ServiceDefaults/Cinema.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
