<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" />
    <PackageReference Include="HotChocolate.Types.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="HotChocolate.Data" />
    <PackageReference Include="HotChocolate.Data.EntityFramework" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <ProjectReference Include="../../SharedKernel/Cinema.SharedKernel.csproj" />
    <ProjectReference Include="../../ServiceDefaults/Cinema.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
