@host = http://localhost:5519

POST {{host}}/notes
Content-Type: application/json

{
  "title": "groceries",
  "content": "milk"
}

###

GET {{host}}/notes

###

GET {{host}}/notes/1

###

PUT {{host}}/notes/1
Content-Type: application/json

{
  "title": "errands",
  "content": "bread"
}

###

DELETE {{host}}/notes/1
