<Project Sdk="Aspire.AppHost.Sdk/13.5.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>5e47d414-43d7-47d7-9181-6dd1e1e21278</UserSecretsId>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="HotChocolate.Fusion.Aspire" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Gateway/Cinema.Gateway.csproj" />
    <ProjectReference Include="../Services/Catalog/Cinema.Catalog.csproj" />
    <ProjectReference Include="../Services/Seating/Cinema.Seating.csproj" />
    <ProjectReference Include="../Services/Pricing/Cinema.Pricing.csproj" />
    <ProjectReference Include="../Services/Ordering/Cinema.Ordering.csproj" />
    <ProjectReference Include="../Services/Payments/Cinema.Payments.csproj" />
    <ProjectReference Include="../Services/Ticketing/Cinema.Ticketing.csproj" />
    <ProjectReference Include="../Services/Loyalty/Cinema.Loyalty.csproj" />
    <ProjectReference Include="../Services/Concessions/Cinema.Concessions.csproj" />
    <ProjectReference Include="../Services/Identity/Cinema.Identity.csproj" />
    <ProjectReference Include="../Services/Notifications/Cinema.Notifications.csproj" />
  </ItemGroup>

</Project>
